# Generated by Django 3.1 on 2020-08-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fibonacci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_val', models.IntegerField()),
            ],
        ),
    ]
