# Generated by Django 3.1 on 2020-08-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_fibonacci'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
