# Generated by Django 3.1 on 2020-08-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_auto_20200814_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='InputForm',
        ),
    ]
