# Generated by Django 3.1 on 2020-08-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_auto_20200817_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pythagorean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
